ALTER TABLE airlines DISABLE ROW LEVEL SECURITY;
ALTER TABLE agreements DISABLE ROW LEVEL SECURITY;
ALTER TABLE integration_milestones DISABLE ROW LEVEL SECURITY;
ALTER TABLE usage_metrics DISABLE ROW LEVEL SECURITY;
ALTER TABLE penalty_ledger DISABLE ROW LEVEL SECURITY;
